version: '3.4'

services:
  garage.service:
    image: ${DOCKER_REGISTRY-}garageservice
    build:
      context: .
      dockerfile: Garage.Service/Dockerfile
    restart: always
  #web:
  #  image: nginx
  #  ports:
  #   - "55101:80"
  #  environment:
  #   - NGINX_PORT=55101
  #  restart: always