version: '3.4'

services:
  garage.service:
    image: ${DOCKER_REGISTRY-}garageservice
    build:
      context: ../
      dockerfile: GarageOpener/Garage.Service/Dockerfile
    restart: always
  ngrok:
    image: wernight/ngrok:armhf
    restart: always