services:
  garage.service:
    image: npizzo92/garageservice
    restart: always
    privileged: true
    environment:
      - ASPNETCORE_ENVIRONMENT=Home
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=password
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/home.pfx
      - TogglePin=4
      - ClosedPin=6
      - TokenKey=<sometoken>
    ports:
      - "8000:80"
      - "8001:443"
    volumes:
      - ./keys:/https:ro
  homeautomation.web:
    image: npizzo92/pizzohomeautomationblazor
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Home
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=password
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/home.pfx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./keys:/https:ro