version: '3.4'

services:
  garage.service:
    image: npizzo92/garageservice
    restart: always
    privileged: true
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - TogglePin=4
      - ClosedPin=6
      - TokenKey=<sometoken>
    ports:
      - "8000:80"
  ngrok:
    image: wernight/ngrok:armhf
    restart: always
    environment:
      NGROK_AUTH: <key>
      NGROK_PORT: http://garage.service:80
    ports:
      - "4040:4040"