services:
  garage.service:
    image: npizzo92/garageservice
    restart: always
    privileged: true
    environment:
      - ASPNETCORE_ENVIRONMENT=Home
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - TogglePin=4
      - ClosedPin=26
      - TokenKey=<sometoken>
    ports:
      - "8000:80"
      - "8001:443"
    volumes:
      - /home/pi/certs:/home
  homeautomation.web:
    image: npizzo92/pizzohomeautomationblazor
    restart: always
    depends_on:
      - garage.service
    environment:
      - ASPNETCORE_ENVIRONMENT=Home
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - LettuceEncrypt__DomainNames__0=example.com
      - LettuceEncrypt__CertDirectory="/home"
      - LettuceEncrypt__CertPassword=password
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /home/pi/certs:/home