version: '3.4'

services:
  garage.service:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - TogglePin=4
      - ClosedPin=6
      - TokenKey=Testing123
    ports:
      - "8000:80"