version: '3.4'

services:
  garage.service:
    image: npizzo92/garageservice
    restart: always
    privileged: true
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - TogglePin=4
      - ClosedPin=6
      - TokenKey=<sometoken>
    ports:
      - "8000:80"
  azure.proxy:
    image: npizzo92/azurehybridconnectionproxyservice
    restart: always
    environment:
       - AZHybridConnectionOptions__RelayNamespace=<relayNamespace>
       - AZHybridConnectionOptions__RelayConnectionName=<connectionName>
       - AZHybridConnectionOptions__KeyName=<keyName>
       - AZHybridConnectionOptions__Key=<key>
       - AZHybridConnectionOptions__ForwaredHost=<host>